# Generated by Django 3.2.5 on 2021-09-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muffin',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
    ]
